apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: friend-deployment
  namespace: monitoring
  labels: 
    prometheus: main 
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: friend-deployment
  endpoints:
  - port: http
    path: '/actuator/prometheus'
    interval: 10s
    honorLabels: true