---
apiVersion: v1
kind: Service
metadata:
  name: friend-service
  namespace: monitoring

spec:
  type: ClusterIP
  selector:
    app: friend-deployment
  ports:
  - name: http
    port: 80
    targetPort: 7001
