---

# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: monitoring
  
spec:
  selector:
    app: discovery-service
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8761