kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-data-storage
  namespace: neo4j

  labels:
    type: local
    app: neo4j
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: db
  hostPath:
    path: "data/neo4j/db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-plugin-storage
  namespace: neo4j

  labels:
    type: local
    app: neo4j
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: db
  hostPath:
    path: "data/neo4j/db"