kind: PersistentVolumeClaim 
apiVersion: v1
metadata:
  name: neo4j-data-claim
  namespace: neo4j
  labels:
    app: neo4j-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
  kind: PersistentVolumeClaim         
  apiVersion: v1
  metadata:
    name: neo4j-plugin-claim
    namespace: neo4j
    labels:
      app: neo4j-db
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi