--- 
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8090
