
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-broker
  namespace: default

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
  namespace: default

data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9191
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:

      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9191

        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_BROKER_ID

        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_ZOOKEEPER_CONNECT

        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP

        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_ADVERTISED_LISTENERS

        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR

        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR

        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR

        # env:
        # - name: KAFKA_ADVERTISED_PORT
        #   value: "30718"
        # - name: KAFKA_ADVERTISED_HOST_NAME
        #   value: 192.168.1.240
        # - name: KAFKA_ZOOKEEPER_CONNECT
        #   value: zoo1:2181
        # - name: KAFKA_BROKER_ID
        #   value: "0"
        # - name: KAFKA_CREATE_TOPICS
        #   value: admintome-test:1:1


---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default

  labels:
    name: kafka
spec:
  ports:
  - port: 9191
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer
