---

- name: Add APT key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    # url: https://pkg.jenkins.io/debian/jenkins-ci.org.key

- name: Copy jenkins.list to /etc/apt/sources.list.d/jenkins.list
  copy:
    src: jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list

- name: Install Jenkins
  apt: 
    name: jenkins
    update_cache: yes
    install_recommends: no


- name: Add Jenkins to Docker Group
  command: sudo usermod -a -G docker jenkins

- name: Restart Jenkins 
  command: sudo service jenkins restart