---
# - name: Ensure Nginx is at the latest version
#   apt:
#     name: nginx
#     state: latest
# - name: Make sure Nginx is running
#   systemd:
#     state: started
#     name: nginx

# ---
- name: Install JRE and JDK
  apt:
    name: "{{ jenkins_jdk }}"
    install_recommends: no
    update_cache: yes
- name: Add APT key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    # url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
- name: Copy jenkins.list to /etc/apt/sources.list.d/jenkins.list
  copy:
    src: jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list

- name: Install Jenkins
  apt: 
    name: jenkins
    update_cache: yes
    install_recommends: no
