---

- name: Install Java
  apt: 
    name:  "{{ item }}"
    update_cache: yes
    install_recommends: no
    items: 
    - "openjdk-17-jre"
    - "openjdk-17-jdk"

- name: Get Apt Key
  yum_repository:
    name:  jenkins-ci
    baseurl:  https://pkg.jenkins.io/debian-stable
    description:  jenkins-ci package repository
    gpgcheck:  yes
    gpgkey:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    enabled: true
    state: present

- name: Copy jenkins.list to sources list/ jenkins listen_ports_facts
  copy:
    src: jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list

- name: Install Jenkins
  apt: 
    name: jenkins
    update_cache: yes
    install_recommends: no

- name: Ensure jenkins service added to firewalld
  firewalld:
    service: jenkins
    state: enabled
    permanent: yes
    immediate: yes

- name: Ensure port 8080 added to firewalld
  firewalld:
    port: 8080/tcp
    state: enabled
    permanent: yes
    immediate: yes
    
# - name: Ensure GPG key is imported
#   yum: 
#     name: jenkins 
#     update_cache: yes
#     state: present
#   shell: | 
#     curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
#       /usr/share/keyrings/jenkins-keyring.asc > /dev/null
#     echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
#       https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
#       /etc/apt/sources.list.d/jenkins.list > /dev/null
#     sudo apt-get update
#     sudo apt-get install jenkins

  