
##################################################
#
#  To use:  `kubectl apply -f application.yml`
#
##################################################
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd-updater
  # Force Argo to delete this instance as well
  annotations:
    # argocd-image-updater.argoproj.io/image-list: philipasd/app:~v1.0
    argocd-image-updater.argoproj.io/image-list: philipasd/app
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/write-back-method: git  # all git options are supported
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/philipasd/app.update-strategy: latest
    # argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    
    

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/philipdaquin/friend-recommendation-infra.git
    targetRevision: master
    # Point to the deployment.yaml
    path: environments/staging/app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true