---
apiVersion: v1
kind: Secret
metadata:
  name: friend-recommendation-infra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:philipdaquin/friend-recommendation-infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCQzwBnpsnligQ2Tfd1Sm6mkvlYcwjrDd7nxb4/VBA6XAAAAKAWhbrSFoW6
    0gAAAAtzc2gtZWQyNTUxOQAAACCQzwBnpsnligQ2Tfd1Sm6mkvlYcwjrDd7nxb4/VBA6XA
    AAAEABQgzoFxd8ys77oa+ICU+5VzTM9Hs+BULabkWFy8Tc0pDPAGemyeWKBDZN93VKbqaS
    +VhzCOsN3ufFvj9UEDpcAAAAGHBoaWxpcGRhcXVpbjIwQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"