---
apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/philipdaquin/friend-recommendation-infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAiDn9CfTaycP8MtiLTFyI9BlhCSA/79NCiE3MQ/3cDYQAAAKABii6BAYou
    gQAAAAtzc2gtZWQyNTUxOQAAACAiDn9CfTaycP8MtiLTFyI9BlhCSA/79NCiE3MQ/3cDYQ
    AAAECdyM2da6S0iIs+/lhcfWBDqLxrQto5DuHWdV409UiCQCIOf0J9NrJw/wy2ItMXIj0G
    WEJID/v00KITcxD/dwNhAAAAGHBoaWxpcGRhcXVpbjIwQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"