

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: monitoring
spec:
  type:  ClusterIP 
  selector:
    app: user-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 7000
  