server:
  additionalApplications:
    - name: argocd-staging
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/philipdaquin/friend-recommendation-infra.git
        targetRevision: HEAD
        path: /deployment
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespaces: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false