---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: monitoring

spec:
  type: ClusterIP
  selector:
    app: recommendation-deployment
  ports:
  - name: http
    protocol: TCP 
    port: 80
    targetPort: 7002


