
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  annotations:
    # The image you want to monitor
    argocd-image-updater.argoproj.io/image-list: philipasd/app:~v0.4
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/philipdaquin/friend-recommendation-infra.git
    
    targetRevision: master
    #  Point to the Helm Charts
    path: appservice

    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: philipasd/app
        - name: "image.tag"
          value: v1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true