
##################################################
#
#  To use:  `kubectl apply -f application.yml`
#
##################################################
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: philipasd/friend_service
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: ssh://git@github.com/philipdaquin/friend-recommendation-infra.git
    targetRevision: main
    path: friend_service
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: philipasd/friend_service
        - name: "image.tag"
          value: v0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

