---
apiVersion: v1
kind: Secret
metadata:
  name: friend-recommendation-infra
  namespace: argocd
  labels: 
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:philipdaquin/friend-recommendation-infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAiwn/tPnr9kutu4UMpZhwJhNjWXfe8eHCvz66Zv5jHpQAAAKBRg1YyUYNW
    MgAAAAtzc2gtZWQyNTUxOQAAACAiwn/tPnr9kutu4UMpZhwJhNjWXfe8eHCvz66Zv5jHpQ
    AAAEAnuBQaJ3zwQ7/9KDkVmnIUygH4Z8DKcYHukGdzPaRwsiLCf+0+ev2S627hQylmHAmE
    2NZd97x4cK/Prpm/mMelAAAAGHBoaWxpcGRhcXVpbjIwQGdtYWlsLmNvbQECAwQF
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"