


---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-db

---


apiVersion: v1
kind: Service
metadata:
  name: redis-db
  namespace: redis-db
spec:
  ports:
  - port: 6379
    name: peer
  clusterIP: None
  selector:
    app: redis-db