---
# defaults file for ansible


jenkins_jre: openjdk-17-jre
jenkins_jdk: openjdk-17-jdk
container_count: 4
default_container_name: docker
default_container_image: ubuntu
default_container_command: sleep 1d