---

- name:  Install Jenkins
  hosts: localhost
  remote_user: aws 
  become: yes

  tasks:  
    - name: Update apt
      apt:
        update_cache: yes
    

    
    - name: Download Docker

    - name: Download Long Term Jenkins Release 
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo